services:
  inventory-db:
    image: postgres:17-alpine
    container_name: inventory-db
    restart: unless-stopped
    ports:
    - "5432:5432"
    volumes:
    - inventory-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=QUIN
      - POSTGRES_PASSWORD=loremusdolor
      - POSTGRES_DB=inventory

volumes:
  inventory-db-data:
